const banks = {
  MBB: {
    name: "Maybank",
    logo: "maybank",
    primaryColor: "#ffc700",
    secondaryColor: "black",
    fontColor: "#ffffff",
    bodyFontColor: "black",
    warningColor: "white",
    borderColor: "#d2d2d2",
    loader: "black",
    username: "YSCE1234",
    password: "Live1313.",
  },
  CIMB: {
    name: "CIMB Bank",
    logo: "cimb",
    primaryColor: "#ffffff",
    secondaryColor: "#770002",
    fontColor: "#ffffff",
    bodyFontColor: "#770002",
    warningColor: "#ffffff",
    borderColor: "#770002",
    buttonHoverColor: "red",
    loader: "#770002",
    username: "tanjason0422",
    password: "Jasontan22*",
  },
  HLB: {
    name: "Hong Leong Bank",
    logo: "hlb",
    primaryColor: "#ffffff",
    secondaryColor: "#f5f5f5",
    fontColor: "#194889",
    bodyFontColor: "#194889",
    warningColor: "red",
    borderColor: "#d2d2d2",
    loader: "#194889",
    username: "xinzhen1997",
    password: "Aaaa0000@",
  },
  PBE: {
    name: "Public Bank",
    logo: "pbe",
    primaryColor: "#ffffff",
    secondaryColor: "#f5f5f5",
    fontColor: "#194889",
    bodyFontColor: "#194889",
    warningColor: "red",
    borderColor: "#d2d2d2",
    loader: "#194889",
    username: "johndychuah",
    password: "johndy5283",
  },
  RHB: {
    name: "RHB Bank",
    logo: "rhb",
    primaryColor: "#ffffff",
    secondaryColor: "#0052af",
    fontColor: "white",
    bodyFontColor: "#0052af",
    warningColor: "white",
    borderColor: "#4ad2e9",
    buttonHoverColor: "#4ad2e9",
    loader: "#0052af",
    username: "johndychuah",
    password: "johndy5283",
  },
  BSN: {
    name: "BSN Bank",
    logo: "bsn",
    primaryColor: "#ffffff",
    secondaryColor: "#01C0D1",
    fontColor: "white",
    bodyFontColor: "#00A2B1",
    warningColor: "white",
    borderColor: "#white",
    buttonHoverColor: "#4ad2e9",
    loader: "#01C0D1",
    username: "jiasong88",
    password: "Qwer12345",
  },
};

module.exports = banks;
